In [1]:
import json
import urllib
import requests
import pandas as pd
from sqlalchemy import create_engine

### Extract Car Data

In [2]:
#data source 1 Car API
url = 'https://parseapi.back4app.com/classes/Carmodels_Car_Model_List?limit=100'
headers = {
    'X-Parse-Application-Id': '5gbW8wxzVzU0r7PUf3wZSEkEy1zssIglkpftKP09', # This is your app's application id
    'X-Parse-REST-API-Key': 'YshIZmvNeYVIexjU3GlhHph7xtLEbpCXOF18gDa3' # This is your app's REST API key
}
data = json.loads(requests.get(url, headers=headers).content.decode('utf-8')) # Here you have the data that you need
print(json.dumps(data, indent=2))

{
  "results": [
    {
      "objectId": "ZRgPP9dBMm",
      "Year": 2020,
      "Make": "Audi",
      "Model": "Q3",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "cptB1C1NSL",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Malibu",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ElhqsRZDnP",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "Escalade ESV",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "LUzyWMYJpW",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Corvette",
      "Category": "Coupe, Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rDkHakOBKP",
      "Year": 2020,
      "Make": "Acura",
      "Model": "RLX",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "1JARpJ2AUB",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Silverado 2500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "7G1VT2pSNO",
      "Year": 2020,
      "Make": "BMW",
      "Model": "3 Series",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "4q7L9FAU2S",
      "Year": 2020,
      "Make": "Chrysler",
      "Model": "Pacifica",
      "Category": "Van/Minivan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "jpOC5zs3jx",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Colorado Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "96llWfTOAe",
      "Year": 2020,
      "Make": "BMW",
      "Model": "X3",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "5OEvsF1R9k",
      "Year": 2020,
      "Make": "Acura",
      "Model": "TLX",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "LNq3duGh9z",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Silverado 3500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "FThs77Cddn",
      "Year": 2020,
      "Make": "BMW",
      "Model": "7 Series",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "t9eGFMIk7E",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Fusion",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "cWQjuYWwc2",
      "Year": 2020,
      "Make": "Buick",
      "Model": "Envision",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "2lYY81jKzR",
      "Year": 2020,
      "Make": "Audi",
      "Model": "SQ5",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "qGDd5H3yYd",
      "Year": 2020,
      "Make": "Audi",
      "Model": "R8",
      "Category": "Coupe, Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ALbinxfzM1",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Traverse",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "9eRGwnViia",
      "Year": 2020,
      "Make": "Acura",
      "Model": "MDX",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "kAgBF7aSaO",
      "Year": 2020,
      "Make": "INFINITI",
      "Model": "QX80",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "ygsDiv3hRm",
      "Year": 2020,
      "Make": "Buick",
      "Model": "Encore",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "92pfQo6pA4",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Sierra 2500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VfXndYon3e",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Insight",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "grl6dVnzM9",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "XT6",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "QrYfmqcnAR",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "XT5",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "hSaQDQkkE0",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "XT4",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rSQyj88Pwe",
      "Year": 2020,
      "Make": "Buick",
      "Model": "Enclave",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "kkcmfophql",
      "Year": 2020,
      "Make": "Audi",
      "Model": "Q5",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "V1F5kE5svr",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Santa Fe",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "bW6jRQ3h2S",
      "Year": 2020,
      "Make": "Ford",
      "Model": "EcoSport",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "6YcNNwgY0C",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Escape",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "dxs3ayh6Yl",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Mustang",
      "Category": "Coupe, Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "yZUeGC1bOn",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Sonata",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "JyMpQJbCvy",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Edge",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VT4rtTsGBj",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Camaro",
      "Category": "Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "vRQFNeVlsa",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Kona Electric",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "OHHuEGKsUC",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Equinox",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "vu2lCeXKzk",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Sierra 3500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rg8LbH5ixZ",
      "Year": 2020,
      "Make": "Jeep",
      "Model": "Gladiator",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "ifEdBTIVDH",
      "Year": 2020,
      "Make": "BMW",
      "Model": "X7",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "4J2BvKonKq",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "CT6-V",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "PlNwrAm6eM",
      "Year": 2020,
      "Make": "Audi",
      "Model": "A7",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VK6hmDAvqP",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Blazer",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "vidGAd8cIJ",
      "Year": 2020,
      "Make": "Ford",
      "Model": "F150 SuperCrew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "NHWgNGSFB7",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Suburban",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "MTvnyKqtYJ",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Civic",
      "Category": "Hatchback, Sedan, Coupe",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "wTXL9Ze5eF",
      "Year": 2020,
      "Make": "Jeep",
      "Model": "Compass",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "SCG7WEYdG1",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "Escalade",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "cKnegrw5AO",
      "Year": 2020,
      "Make": "Chrysler",
      "Model": "Voyager",
      "Category": "Van/Minivan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "smKxD5m9KI",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Accord Hybrid",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ED6o8Zffqs",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Terrain",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "2ZCPYTGxDj",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Spark",
      "Category": "Hatchback",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "fZGBnnMx4e",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Sierra 1500 Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "6qsEYBv6eW",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "NEXO",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "4lZKmYPbMk",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Veloster",
      "Category": "Coupe",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "9BdK0PtwKc",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Silverado 1500 Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "H1THLG6H1Z",
      "Year": 2020,
      "Make": "Genesis",
      "Model": "G70",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "XtDg7lwyJT",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "CT5",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "KE29kkqLX6",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Odyssey",
      "Category": "Van/Minivan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "70EmSYGau7",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Elantra GT",
      "Category": "Hatchback",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "YZj6RLht79",
      "Year": 2020,
      "Make": "Acura",
      "Model": "RDX",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "3phIrCVLh7",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Yukon XL",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "i6jT5ByjBF",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Ranger SuperCab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "RHD7qDmzgU",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Expedition MAX",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "pJCLIx2r8E",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Kona",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "8kzM0APnBF",
      "Year": 2020,
      "Make": "INFINITI",
      "Model": "QX50",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "1AV4avrH6j",
      "Year": 2020,
      "Make": "Dodge",
      "Model": "Durango",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "dow9fD3WF6",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Yukon",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "adJr9Qr42Q",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Palisade",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "F7BG83iyWo",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Ridgeline",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VMpSU5DhdC",
      "Year": 2020,
      "Make": "Jeep",
      "Model": "Cherokee",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "UY03j6Fe12",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Bolt EV",
      "Category": "Hatchback",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "7zxuFmGDLY",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Expedition",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "pTGFRlqNAZ",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Elantra",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "e5835fdPKX",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Passport",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rYV3CVGElN",
      "Year": 2020,
      "Make": "Dodge",
      "Model": "Charger",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "DemETgxfzm",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Accord",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ZcDno27E49",
      "Year": 2020,
      "Make": "INFINITI",
      "Model": "QX60",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "eQ15fbmmpw",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Venue",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "bAVM6QBgYF",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Pilot",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "IeeTDLPJtc",
      "Year": 2020,
      "Make": "Jeep",
      "Model": "Grand Cherokee",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "5nK3Kjti74",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Tahoe",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ZnSQK6bmSf",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Acadia",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "MGgtV71Gqh",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Impala",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "QHVcYMkgs8",
      "Year": 2020,
      "Make": "Honda",
      "Model": "CR-V",
      "Category": "SUV",

In [3]:
totalcars = len(data['results'])
totalcars

100

In [4]:
#Define and append lists 
year_list=[]
make_list=[]
category_list=[]
model_list=[]
for car in range(totalcars):
    year_list.append(data['results'][car]['Year'])
    make_list.append(data['results'][car]['Make'])
    model_list.append(data['results'][car]['Model'])
    category_list.append(data['results'][car]['Category'])
    

#print(year_list)
print(make_list)

['Audi', 'Chevrolet', 'Cadillac', 'Chevrolet', 'Acura', 'Chevrolet', 'BMW', 'Chrysler', 'Chevrolet', 'BMW', 'Acura', 'Chevrolet', 'BMW', 'Ford', 'Buick', 'Audi', 'Audi', 'Chevrolet', 'Acura', 'INFINITI', 'Buick', 'GMC', 'Honda', 'Cadillac', 'Cadillac', 'Cadillac', 'Buick', 'Audi', 'Hyundai', 'Ford', 'Ford', 'Ford', 'Hyundai', 'Ford', 'Chevrolet', 'Hyundai', 'Chevrolet', 'GMC', 'Jeep', 'BMW', 'Cadillac', 'Audi', 'Chevrolet', 'Ford', 'Chevrolet', 'Honda', 'Jeep', 'Cadillac', 'Chrysler', 'Honda', 'GMC', 'Chevrolet', 'GMC', 'Hyundai', 'Hyundai', 'Chevrolet', 'Genesis', 'Cadillac', 'Honda', 'Hyundai', 'Acura', 'GMC', 'Ford', 'Ford', 'Hyundai', 'INFINITI', 'Dodge', 'GMC', 'Hyundai', 'Honda', 'Jeep', 'Chevrolet', 'Ford', 'Hyundai', 'Honda', 'Dodge', 'Honda', 'INFINITI', 'Hyundai', 'Honda', 'Jeep', 'Chevrolet', 'GMC', 'Chevrolet', 'Honda', 'BMW', 'INFINITI', 'Ford', 'Chevrolet', 'Hyundai', 'Jaguar', 'Hyundai', 'Ford', 'Honda', 'Jaguar', 'INFINITI', 'Genesis', 'Jaguar', 'Jeep', 'Hyundai']

In [5]:
#Create dataframe from lists
SummaryTable = pd.DataFrame({
        "year":year_list,
        "make":make_list,
        "model":model_list,
        'category_list':category_list,
        
})
SummaryTable

    year       make         model       category_list
0   2020       Audi            Q3                 SUV
1   2020  Chevrolet        Malibu               Sedan
2   2020   Cadillac  Escalade ESV                 SUV
3   2020  Chevrolet      Corvette  Coupe, Convertible
4   2020      Acura           RLX               Sedan
..   ...        ...           ...                 ...
95  2020   INFINITI           Q50               Sedan
96  2020    Genesis           G80               Sedan
97  2020     Jaguar        F-PACE                 SUV
98  2020       Jeep      Renegade                 SUV
99  2020    Hyundai        Accent               Sedan

[100 rows x 4 columns]

In [6]:
from bs4 import BeautifulSoup as bs

In [7]:
#Source #2 website scrape
url = 'https://t/2020-us-vehicle-sales-figures-by-brand/'

In [8]:
response = requests.get(url)
response

In [9]:
soup = bs(response.text, 'html.parser')

In [10]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en-US">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="https://gmpg.org/xfn/11" rel="profile"/>
  <meta content="#7dbef4" name="theme-color"/>
  <title>
   2020 U.S. Auto Sales Figures by Brand | GCBC
  </title>
  <script>
   (function(w, d) {
w.adthrive = w.adthrive || {};
w.adthrive.cmd = w.adthrive.cmd || [];
w.adthrive.plugin = 'adthrive-ads-1.0.40';
w.adthrive.host = 'ads.adthrive.com';
var s = d.createElement('script');
s.async = true;
s.referrerpolicy='no-referrer-when-downgrade';
s.src = 'https://' + w.adthrive.host + '/sites/5d9d1ce1963c1233c88539e9/ads.min.js?referrer=' + w.encodeURIComponent(w.location.href);
var n = d.getElementsByTagName('script')[0];
n.parentNode.insertBefore(s, n);
})(window, document);
  </script>
  <!-- All In One SEO Pack 3.7.0ob_start_detected [-1,-1] -->
  <meta content="Monthly, Quarterly and Yearly US Sales Figures by Brand. Ford, Tesla, Chevy, Volkswagen, Subaru, Honda, Mercedes, BMW and More. Includes free interactive tables and charts." name="description">
   <script class="aioseop-schema" type="application/ld+json">
    {"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://www.goodcarbadcar.net/#organization","url":"https://www.goodcarbadcar.net/","name":"GCBC","sameAs":[]},{"@type":"WebSite","@id":"https://www.goodcarbadcar.net/#website","url":"https://www.goodcarbadcar.net/","name":"GCBC","publisher":{"@id":"https://www.goodcarbadcar.net/#organization"}},{"@type":"WebPage","@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#webpage","url":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/","inLanguage":"en-US","name":"2020 US Vehicle Sales Figures By Brand","isPartOf":{"@id":"https://www.goodcarbadcar.net/#website"},"breadcrumb":{"@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#breadcrumblist"},"description":"Monthly, Quarterly and Yearly US Sales Figures by Brand. Ford, Tesla, Chevy, Volkswagen, Subaru, Honda, Mercedes, BMW and More.  Includes free interactive tables and charts.","image":{"@type":"ImageObject","@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#primaryimage","url":"https://www.goodcarbadcar.net/wp-content/uploads/2019/07/joey-kyber-45FJgZMXCK8-unsplash.jpg","width":2048,"height":1322},"primaryImageOfPage":{"@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#primaryimage"},"datePublished":"2020-02-03T17:01:15+00:00","dateModified":"2020-09-01T19:55:12+00:00"},{"@type":"Article","@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#article","isPartOf":{"@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#webpage"},"author":{"@id":"https://www.goodcarbadcar.net/author/wade-thiel/#author"},"headline":"2020 US Vehicle Sales Figures By Brand","datePublished":"2020-02-03T17:01:15+00:00","dateModified":"2020-09-01T19:55:12+00:00","commentCount":0,"mainEntityOfPage":{"@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#webpage"},"publisher":{"@id":"https://www.goodcarbadcar.net/#organization"},"articleSection":"Top Level Reports, Sales By Brand, US Auto Sales, US Top Level, 2020, 2020, 2020 Sales By Brand, 2020 Top Level Reports, sales by brand, Top Level Reports, US Auto Sales, US Top Level","image":{"@type":"ImageObject","@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#primaryimage","url":"https://www.goodcarbadcar.net/wp-content/uploads/2019/07/joey-kyber-45FJgZMXCK8-unsplash.jpg","width":2048,"height":1322}},{"@type":"Person","@id":"https://www.goodcarbadcar.net/author/wade-thiel/#author","name":"Wade Thiel","sameAs":["https://twitter.com/WadeThiel"],"image":{"@type":"ImageObject","@id":"https://www.goodcarbadcar.net/#personlogo","url":"https://www.goodcarbadcar.net/wp-content/uploads/2019/01/wadethiel.jpg","width":96,"height":96,"caption":"Wade Thiel"}},{"@type":"BreadcrumbList","@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/#breadcrumblist","itemListElement":[{"@type":"ListItem","position":1,"item":{"@type":"WebPage","@id":"https://www.goodcarbadcar.net/","url":"https://www.goodcarbadcar.net/","name":"Auto Sales Data | Canada &amp; the USA | GoodCarBadCar.net"}},{"@type":"ListItem","position":2,"item":{"@type":"WebPage","@id":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/","url":"https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/","name":"2020 US Vehicle Sales Figures By Brand"}}]}]}
   </script>
   <link href="https://www.goodcarbadcar.net/2020-us-vehicle-sales-figures-by-brand/" rel="canonical">
    <!-- All In One SEO Pack -->
    <link href="//www.google-analytics.com" rel="dns-prefetch"/>
    <link href="//fonts.googleapis.com" rel="dns-prefetch"/>
    <link href="//s.w.org" rel="dns-prefetch"/>
    <link href="https://www.goodcarbadcar.net/feed/" rel="alternate" title="GCBC » Feed" type="application/rss+xml"/>
    <link href="https://www.goodcarbadcar.net/comments/feed/" rel="alternate" title="GCBC » Comments Feed" type="application/rss+xml"/>
    <script type="text/javascript">
     window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/13.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/www.goodcarbadcar.net\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.5"}};
!function(e,a,t){var r,n,o,i,p=a.createElement("canvas"),s=p.getContext&&p.getContext("2d");function c(e,t){var a=String.fromCharCode;s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,e),0,0);var r=p.toDataURL();return s.clearRect(0,0,p.width,p.height),s.fillText(a.apply(this,t),0,0),r===p.toDataURL()}function l(e){if(!s||!s.fillText)return!1;switch(s.textBaseline="top",s.font="600 32px Arial",e){case"flag":return!c([127987,65039,8205,9895,65039],[127987,65039,8203,9895,65039])&&(!c([55356,56826,55356,56819],[55356,56826,8203,55356,56819])&&!c([55356,57332,56128,56423,56128,56418,56128,56421,56128,56430,56128,56423,56128,56447],[55356,57332,8203,56128,56423,8203,56128,56418,8203,56128,56421,8203,56128,56430,8203,56128,56423,8203,56128,56447]));case"emoji":return!c([55357,56424,8205,55356,57212],[55357,56424,8203,55356,57212])}return!1}function d(e){var t=a.createElement("script");t.src=e,t.defer=t.type="text/javascript",a.getElementsByTagName("head")[0].appendChild(t)}for(i=Array("flag","emoji"),t.supports={everything:!0,everythingExceptFlag:!0},o=0;o<i.length;o++)t.supports[i[o]]=l(i[o]),t.supports.everything=t.supports.everything&&t.supports[i[o]],"flag"!==i[o]&&(t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&t.supports[i[o]]);t.supports.everythingExceptFlag=t.supports.everythingExceptFlag&&!t.supports.flag,t.DOMReady=!1,t.readyCallback=function(){t.DOMReady=!0},t.supports.everything||(n=function(){t.readyCallback()},a.addEventListener?(a.addEventListener("DOMContentLoaded",n,!1),e.addEventListener("load",n,!1)):(e.attachEvent("onload",n),a.attachEvent("onreadystatechange",function(){"complete"===a.readyState&&t.readyCallback()})),(r=t.source||{}).concatemoji?d(r.concatemoji):r.wpemoji&&r.twemoji&&(d(r.twemoji),d(r.wpemoji)))}(window,document,window._wpemojiSettings);
    </script>
    <style type="text/css">
     img.wp-smiley,
img.emoji {
display: inline !important;
border: none !important;
box-shadow: none !important;
height: 1em !important;
width: 1em !important;
margin: 0 .07em !important;
vertical-align: -0.1em !important;
background: none !important;
padding: 0 !important;
}
    </style>
    <!-- <link rel='stylesheet' id='wp-block-library-css'  href='https://www.goodcarbadcar.net/wp-includes/css/dist/block-library/style.min.css?ver=5.5' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='lets-info-up-style-css-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/lets-info-up/admin/block/dist/blocks.style.build.css?ver=1.1.3' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='lets-review-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/lets-review/frontend/css/lets-review-style.min.css?ver=2.6.2' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='lets-social-count-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/lets-social-count/assets/css/style.css?ver=1.1' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='tablepress-columnfilterwidgets-css-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/tablepress-datatables-column-filter-widgets/css/ColumnFilterWidgets.min.css?ver=1.2' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='cookie-consent-style-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/uk-cookie-consent/assets/css/style.css?ver=5.5' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='lets-info-up-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/lets-info-up/frontend/css/style.min.css?ver=1.1.3' type='text/css' media='all' /> -->
    <link href="//www.goodcarbadcar.net/wp-content/cache/wpfc-minified/7wvfdsgw/bmwzk.css" media="all" rel="stylesheet" type="text/css"/>
    <style id="lets-info-up-inline-css" type="text/css">
     .lets-info-up-wrap-49565 { background: #f5f5f5; } .lets-info-up-wrap-49565, .lets-info-up-wrap-49565 a { color: #000000!important; }
    </style>
    <!-- <link rel='stylesheet' id='lets-live-blog-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/lets-live-blog/frontend/css/style.min.css?ver=1.1.0' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='lets-live-blog-icons-css'  href='https://www.goodcarbadcar.net/wp-content/plugins/lets-live-blog/frontend/css/fonts/style.css?ver=1.1.0' type='text/css' media='all' /> -->
    <!-- <link rel='stylesheet' id='zeen-style-css'  href='https://www.goodcarbadcar.net/wp-content/themes/zeen/assets/css/style.min.css?ver=2.1.0' type='text/css' media='all' /> -->
    <link href="//www.goodcarbadcar.net/wp-content/cache/wpfc-minified/ef98f43c/bmwzk.css" media="all" rel="stylesheet" type="text/css"/>
    <style id="zeen-style-inline-css" type="text/css">
     .content-bg, .article-layout-skin-1.title-cut-bl .hero-wrap .meta:before, .article-layout-skin-1.title-cut-bc .hero-wrap .meta:before, .standard-archive .page-header { background: #ffffff;}.site-inner { background-color: #fff; }.inline-post .block article .title { font-size: 20px;}.widget-title { font-size:12px;}.fontfam-1 {
font-family: 'Playfair Display', sans-serif!important;
letter-spacing: 0em;	}.body-f1, .quotes-f1 blockquote, .quotes-f1 q, .by-f1 .byline, .sub-f1 .subtitle, .wh-f1 .widget-title, .headings-f1 h1, .headings-f1 .price, .headings-f1 h2, .headings-f1 h3, .headings-f1 h4, .headings-f1 h5, .headings-f1 h6, .font-1, div.jvectormap-tip {font-family: 'Playfair Display', sans-serif;letter-spacing: 0em;font-weight: 900;}.fontfam-2 { font-family: 'Source Serif Pro', serif!important;
letter-spacing: 0em;	}input[type=submit], button, .tipi-button,.button,.body-f2, .quotes-f2 blockquote, .quotes-f2 q, .by-f2 .byline, .sub-f2 .subtitle, .wh-f2 .widget-title, .headings-f2 h1, .headings-f2 h2, .headings-f2 h3, .headings-f2 h4, .headings-f2 h5, .headings-f2 h6, .font-2 {font-family: 'Source Serif Pro', serif;letter-spacing: 0em;font-weight: 400;}.fontfam-3 { font-family: 'Montserrat', sans-serif!important;
letter-spacing: 0em;	}.body-f3, .quotes-f3 blockquote, .quotes-f3 q, .by-f3 .byline, .sub-f3 .subtitle, .wh-f3 .widget-title, .headings-f3 h1, .headings-f3 h2, .headings-f3 h3, .headings-f3 h4, .headings-f3 h5, .headings-f3 h6, .font-3 {font-family: 'Montserrat', sans-serif;letter-spacing: 0em;font-weight: 400;}.tipi-row, .tipi-builder-on .contents-wrap > p { max-width: 1230px ; }.current-date { color: #f8d92f }.global-accent-border { border-color: #7dbef4; }.trending-accent-border { border-color: #7dbef4; }.trending-accent-bg { border-color: #7dbef4; }.tipi-button.block-loader, .wpcf7-submit { background: #18181e; }.global-accent-bg, .icon-base-2:hover .icon-bg, #progress { background-color: #7dbef4; }.global-accent-text, .mm-submenu-2 .mm-51 .menu-wrap > .sub-menu > li > a { color: #7dbef4; }body { color:#000000;}.excerpt { color:#444;}.read-more-wrap { color:#767676;}blockquote:not(.comment-excerpt) { color:#111;}.byline, .byline a { color:#888;}.preview-classic .meta .title, .preview-thumbnail .meta .title { color:#111;}h1, h2, h3, h4, h5, h6, .block-title { color:#111;}.sidebar-widget  .widget-title { color:#111!important;}.link-color-wrap a { color: #7dbef4; }.copyright { color: #555; }.link-color-wrap a:hover { color: #000; }body {font-size: 15px;line-height:1.6666666666667; }.main-navigation .horizontal-menu, .main-navigation .menu-item {font-weight: 700;}.secondary-wrap .horizontal-menu, .secondary-wrap .menu-item {font-weight: 700;}.footer-lower-area, .footer-lower-area .menu-item {font-weight: 700;}.widget-title {font-weight: 700!important;}.entry-title{ text-transform: none; }.block-wrap-slider .title-wrap .title{ text-transform: none; }.block-wrap-grid .title-wrap .title, .tile-design-4 .meta .title-wrap .title{ text-transform: none; }.block-wrap-classic .title-wrap .title{ text-transform: none; }.block-title{ text-transform: none; }.meta .excerpt .read-more{ text-transform: uppercase; }.block-subtitle{ text-transform: none; }.byline{ text-transform: none; }.widget-title{ text-transform: none; }.main-navigation{ text-transform: uppercase; }.secondary-wrap{ text-transform: uppercase; }.footer-lower-area .menu-item{ text-transform: uppercase; }.single-content .entry-content h1, .single-content .entry-content h2, .single-content .entry-content h3, .single-content .entry-content h4, .single-content .entry-content h5, .single-content .entry-content h6, .bbp__thread__title{ text-transform: none; }.mm-submenu-2 .mm-11 .menu-wrap > *, .mm-submenu-2 .mm-31 .menu-wrap > *, .mm-submenu-2 .mm-21 .menu-wrap > * { border-top: 3px solid transparent; }.separation-border { margin-bottom: 30px; }.block-wrap-classic .inf-spacer + .block:not(.block-62) { margin-top: 30px; }.block-title-wrap-style .block-title:after, .block-title-wrap-style .block-title:before { border-top: 1px #eee solid;}.separation-border-v { background: #eee;}.separation-border-v { height: calc( 100% -  30px - 1px); }@media only screen and (max-width: 480px) {.separation-border { margin-bottom: 30px;}}.sidebar-wrap .sidebar { padding-right: 30px; padding-left: 30px; padding-top:0px; padding-bottom:0px; }.sidebar-left .sidebar-wrap .sidebar { padding-right: 30px; padding-left: 30px; }@media only screen and (min-width: 481px) {.split-1:not(.preview-thumbnail) .mask {
-webkit-flex: 0 0 calc( 50% - 15px);
-ms-flex: 0 0 calc( 50% - 15px);
flex: 0 0 calc( 50% - 15px);
width: calc( 50% - 15px);
}.split-1.preview-1:not(.article-window):not(.preview-thumbnail) .mask { padding-bottom:32%; }}@media only screen and (min-width: 768px) {.hero-meta.tipi-m-typo .title { font-size: 44px; }.hero-meta.tipi-m-typo .subtitle { font-size: 22px; }.title-contrast .hero-wrap { height: calc( 100vh - 100px ); }.tipi-xs-typo .title  { font-size: 15px; }.tipi-s-typo .title, .ppl-s-3 .tipi-s-typo .title, .preview-1 .title, .preview-21 .title  { font-size: 24px;}.sub-menu a:not(.tipi-button) { font-size: 12px;}.footer-widget-wrap { border-right:1px #333333 solid ; }.footer-widget-wrap .widget_search form, .footer-widget-wrap select { border-color:#333333; }.footer-widget-wrap .zeen-widget { border-bottom:1px #333333 solid ; }.footer-widget-wrap .zeen-widget .preview-thumbnail { border-bottom-color: #333333;}.footer-widget-wrap {
padding-top: 50px;
padding-bottom: 50px;
}.secondary-wrap .menu-padding, .secondary-wrap .ul-padding > li > a {
padding-top: 10px;
padding-bottom: 10px;

In [11]:
#scrape of desired data table from website.  
#This html code was then copied, pasted into VScode, saved as html file, opened in website and copied into a csv file
table = soup.find('table', id="table_6")
print(table)

<table class="scroll responsive display nowrap data-t data-t wpDataTable" data-described-by="table_6_desc" data-wpdatatable_id="6179" id="table_6" style="display: none; ">
<!-- Table header -->
<thead>
<tr>
<th class="wdtheader sort" data-class="expand" style="">brand_name</th> <th class="wdtheader sort numdata integer" style="">Q2 2020</th> <th class="wdtheader sort numdata integer" style="">Q2 2019</th> <th class="wdtheader sort numdata integer" style="">Year To Date</th> <th class="wdtheader sort numdata integer" style="">Year to Date Previous Year</th> <th class="wdtheader sort numdata formula" style="">Change</th> </tr>
</thead>
<!-- /Table header -->
<!-- Table body -->
<tbody>
<tr id="table_6179_row_0">
<td style="">Acura</td>
<td style="">27,458</td>
<td style="">37,382</td>
<td style="">82,712</td>
<td style="">73,767</td>
<td style="">-26.5</td>
</tr>
<tr id="table_6179_row_1">
<td style="">Alfa Romeo</td>
<td style="">3,735</td>
<td style="">4,751</td>
<td style="">7,437</td>
<td style="">9,037</td>
<td style="">-21.4</td>
</tr>
<tr id="table_6179_row_2">
<td style="">Audi</td>
<td style="">34,839</td>
<td style="">53,325</td>
<td style="">76,210</td>
<td style="">101,440</td>
<td style="">-34.7</td>
</tr>
<tr id="table_6179_row_3">
<td style="">BMW</td>
<td style="">50,956</td>
<td style="">82,551</td>
<td style="">113,108</td>
<td style="">156,439</td>
<td style="">-38.3</td>
</tr>
<tr id="table_6179_row_4">
<td style="">Buick</td>
<td style="">35,521</td>
<td style="">55,373</td>
<td style="">69,391</td>
<td style="">107,238</td>
<td style="">-35.9</td>
</tr>
<tr id="table_6179_row_5">
<td style="">Cadillac</td>
<td style="">23,297</td>
<td style="">39,739</td>
<td style="">53,620</td>
<td style="">75,735</td>
<td style="">-41.4</td>
</tr>
<tr id="table_6179_row_6">
<td style="">Chevrolet</td>
<td style="">330,381</td>
<td style="">486,884</td>
<td style="">759,910</td>
<td style="">938,626</td>
<td style="">-32.1</td>
</tr>
<tr id="table_6179_row_7">
<td style="">Chrysler</td>
<td style="">13,857</td>
<td style="">32,831</td>
<td style="">43,802</td>
<td style="">64,422</td>
<td style="">-57.8</td>
</tr>
<tr id="table_6179_row_8">
<td style="">Dodge</td>
<td style="">43,756</td>
<td style="">117,582</td>
<td style="">132,412</td>
<td style="">228,099</td>
<td style="">-62.8</td>
</tr>
<tr id="table_6179_row_9">
<td style="">Fiat</td>
<td style="">1,339</td>
<td style="">2,889</td>
<td style="">2,467</td>
<td style="">5,103</td>
<td style="">-53.7</td>
</tr>
<tr id="table_6179_row_10">
<td style="">Ford</td>
<td style="">411,035</td>
<td style="">613,098</td>
<td style="">900,086</td>
<td style="">1,170,982</td>
<td style="">-33.0</td>
</tr>
<tr id="table_6179_row_11">
<td style="">Genesis</td>
<td style="">3,585</td>
<td style="">5,805</td>
<td style="">10,157</td>
<td style="">10,008</td>
<td style="">-38.2</td>
</tr>
<tr id="table_6179_row_12">
<td style="">GMC</td>
<td style="">101,759</td>
<td style="">151,701</td>
<td style="">220,477</td>
<td style="">277,280</td>
<td style="">-32.9</td>
</tr>
<tr id="table_6179_row_13">
<td style="">Honda</td>
<td style="">266,044</td>
<td style="">370,026</td>
<td style="">760,949</td>
<td style="">703,428</td>
<td style="">-28.1</td>
</tr>
<tr id="table_6179_row_14">
<td style="">Hyundai</td>
<td style="">139,378</td>
<td style="">185,743</td>
<td style="">386,291</td>
<td style="">333,328</td>
<td style="">-25.0</td>
</tr>
<tr id="table_6179_row_15">
<td style="">Infiniti</td>
<td style="">16,097</td>
<td style="">28,743</td>
<td style="">41,653</td>
<td style="">63,058</td>
<td style="">-44.0</td>
</tr>
<tr id="table_6179_row_16">
<td style="">Jaguar</td>
<td style="">4,320</td>
<td style="">6,060</td>
<td style="">11,586</td>
<td style="">16,282</td>
<td style="">-28.7</td>
</tr>
<tr id="table_6179_row_17">
<td style="">Jeep</td>
<td style="">176,713</td>
<td style="">243,477</td>
<td style="">359,380</td>
<td style="">456,281</td>
<td style="">-27.4</td>
</tr>
<tr id="table_6179_row_18">
<td style="">Kia</td>
<td style="">125,302</td>
<td style="">168,248</td>
<td style="">372,741</td>
<td style="">304,844</td>
<td style="">-25.5</td>
</tr>
<tr id="table_6179_row_19">
<td style="">Land Rover</td>
<td style="">14,500</td>
<td style="">21,095</td>
<td style="">36,436</td>
<td style="">46,123</td>
<td style="">-31.3</td>
</tr>
<tr id="table_6179_row_20">
<td style="">Lexus</td>
<td style="">50,458</td>
<td style="">68,944</td>
<td style="">130,243</td>
<td style="">135,735</td>
<td style="">-26.8</td>
</tr>
<tr id="table_6179_row_21">
<td style="">Lincoln</td>
<td style="">21,280</td>
<td style="">25,941</td>
<td style="">46,842</td>
<td style="">50,815</td>
<td style="">-18.0</td>
</tr>
<tr id="table_6179_row_22">
<td style="">Mazda</td>
<td style="">61,199</td>
<td style="">67,722</td>
<td style="">179,043</td>
<td style="">138,553</td>
<td style="">-9.6</td>
</tr>
<tr id="table_6179_row_23">
<td style="">Mercedes-Benz</td>
<td style="">69,505</td>
<td style="">80,463</td>
<td style="">144,770</td>
<td style="">159,130</td>
<td style="">-13.6</td>
</tr>
<tr id="table_6179_row_24">
<td style="">Mini</td>
<td style="">5,288</td>
<td style="">8,678</td>
<td style="">10,524</td>
<td style="">17,583</td>
<td style="">-39.1</td>
</tr>
<tr id="table_6179_row_25">
<td style="">Mitsubishi</td>
<td style="">12,197</td>
<td style="">29,030</td>
<td style="">47,760</td>
<td style="">71,100</td>
<td style="">-58.0</td>
</tr>
<tr id="table_6179_row_26">
<td style="">Nissan</td>
<td style="">161,317</td>
<td style="">322,442</td>
<td style="">393,365</td>
<td style="">653,978</td>
<td style="">-50.0</td>
</tr>
<tr id="table_6179_row_27">
<td style="">Porsche</td>
<td style="">12,193</td>
<td style="">15,233</td>
<td style="">24,177</td>
<td style="">30,257</td>
<td style="">-20.0</td>
</tr>
<tr id="table_6179_row_28">
<td style="">Ram</td>
<td style="">127,682</td>
<td style="">196,155</td>
<td style="">268,168</td>
<td style="">333,168</td>
<td style="">-34.9</td>
</tr>
<tr id="table_6179_row_29">
<td style="">Smart</td>
<td style="">0</td>
<td style="">244</td>
<td style="">0</td>
<td style="">475</td>
<td style="">-100.0</td>
</tr>
<tr id="table_6179_row_30">
<td style="">Subaru</td>
<td style="">136,519</td>
<td style="">182,771</td>
<td style="">376,453</td>
<td style="">339,525</td>
<td style="">-25.3</td>
</tr>
<tr id="table_6179_row_31">
<td style="">Tesla</td>
<td style="">36,800</td>
<td style="">53,300</td>
<td style="">89,600</td>
<td style="">83,900</td>
<td style="">-31.0</td>
</tr>
<tr id="table_6179_row_32">
<td style="">Toyota</td>
<td style="">347,571</td>
<td style="">539,448</td>
<td style="">933,017</td>
<td style="">1,016,373</td>
<td style="">-35.6</td>
</tr>
<tr id="table_6179_row_33">
<td style="">Volkswagen</td>
<td style="">69,933</td>
<td style="">98,736</td>
<td style="">144,998</td>
<td style="">184,608</td>
<td style="">-29.2</td>
</tr>
<tr id="table_6179_row_34">
<td style="">Volvo</td>
<td style="">23,770</td>
<td style="">28,062</td>
<td style="">52,952</td>
<td style="">50,120</td>
<td style="">-15.3</td>
</tr>
</tbody> <!-- /Table body -->
<!-- Table footer -->
<!-- /Table footer -->
</table>

In [12]:
#import data from csv file
Auto_Sales_Table = pd.read_csv (r'/Users/klcurtiss/Desktop/Work for Bootcamp/Rutgers Class Practice/01-Lesson-Plans copy/13-ETL-Project/My ETL Project/Auto_Sales_Table.csv', header = None)
print (Auto_Sales_Table)

                0        1        2        3          4      5
0           Acura   27,458   37,382   69,065     73,767  -26.5
1      Alfa Romeo    3,735    4,751    7,437      9,037  -21.4
2            Audi   34,839   53,325   76,210    101,440  -34.7
3             BMW   50,956   82,551  113,108    156,439  -38.3
4           Buick   35,521   55,373   69,391    107,238  -35.9
5        Cadillac   23,297   39,739   53,620     75,735  -41.4
6       Chevrolet  330,381  486,884  759,910    938,626  -32.1
7        Chrysler   13,857   32,831   43,802     64,422  -57.8
8           Dodge   43,756  117,582  132,412    228,099  -62.8
9            Fiat    1,339    2,889    2,467      5,103  -53.7
10           Ford  411,035  613,098  900,086  1,170,982  -33.0
11        Genesis    3,585    5,805    8,797     10,008  -38.2
12            GMC  101,759  151,701  220,477    277,280  -32.9
13          Honda  266,044  370,026  638,671    703,428  -28.1
14        Hyundai  139,378  185,743  327,930    333,328  -25.0
15       Infiniti   16,097   28,743   41,653     63,058  -44.0
16         Jaguar    4,320    6,060   11,586     16,282  -28.7
17           Jeep  176,713  243,477  359,380    456,281  -27.4
18            Kia  125,302  168,248  315,726    304,844  -25.5
19     Land Rover   14,500   21,095   36,436     46,123  -31.3
20          Lexus   50,458   68,944  130,243    135,735  -26.8
21        Lincoln   21,280   25,941   46,842     50,815  -18.0
22          Mazda   61,199   67,722  152,954    138,553   -9.6
23  Mercedes-Benz   69,505   80,463  144,770    159,130  -13.6
24           Mini    5,288    8,678   10,524     17,583  -39.1
25     Mitsubishi   12,197   29,030   47,760     71,100  -58.0
26         Nissan  161,317  322,442  393,365    653,978  -50.0
27        Porsche   12,193   15,233   24,177     30,257  -20.0
28            Ram  127,682  196,155  268,168    333,168  -34.9
29          Smart        0      244        0        475 -100.0
30         Subaru  136,519  182,771  318,568    339,525  -25.3
31          Tesla   36,800   53,300   89,600     83,900  -31.0
32         Toyota  347,571  539,448  933,017  1,016,373  -35.6
33     Volkswagen   69,933   98,736  144,998    184,608  -29.2
34          Volvo   23,770   28,062   52,952     50,120  -15.3

In [13]:
Auto_Sales_Table.columns

Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')

In [14]:
#rename the header
Auto_Sales_Table.columns = ['make','q2_2020','q2_2019',
                     'year_to_date','year_to_date_previous','change']

In [15]:
print(Auto_Sales_Table)

             make  q2_2020  q2_2019 year_to_date year_to_date_previous  change
0           Acura   27,458   37,382       69,065                73,767   -26.5
1      Alfa Romeo    3,735    4,751        7,437                 9,037   -21.4
2            Audi   34,839   53,325       76,210               101,440   -34.7
3             BMW   50,956   82,551      113,108               156,439   -38.3
4           Buick   35,521   55,373       69,391               107,238   -35.9
5        Cadillac   23,297   39,739       53,620                75,735   -41.4
6       Chevrolet  330,381  486,884      759,910               938,626   -32.1
7        Chrysler   13,857   32,831       43,802                64,422   -57.8
8           Dodge   43,756  117,582      132,412               228,099   -62.8
9            Fiat    1,339    2,889        2,467                 5,103   -53.7
10           Ford  411,035  613,098      900,086             1,170,982   -33.0
11        Genesis    3,585    5,805        8,797                10,008   -38.2
12            GMC  101,759  151,701      220,477               277,280   -32.9
13          Honda  266,044  370,026      638,671               703,428   -28.1
14        Hyundai  139,378  185,743      327,930               333,328   -25.0
15       Infiniti   16,097   28,743       41,653                63,058   -44.0
16         Jaguar    4,320    6,060       11,586                16,282   -28.7
17           Jeep  176,713  243,477      359,380               456,281   -27.4
18            Kia  125,302  168,248      315,726               304,844   -25.5
19     Land Rover   14,500   21,095       36,436                46,123   -31.3
20          Lexus   50,458   68,944      130,243               135,735   -26.8
21        Lincoln   21,280   25,941       46,842                50,815   -18.0
22          Mazda   61,199   67,722      152,954               138,553    -9.6
23  Mercedes-Benz   69,505   80,463      144,770               159,130   -13.6
24           Mini    5,288    8,678       10,524                17,583   -39.1
25     Mitsubishi   12,197   29,030       47,760                71,100   -58.0
26         Nissan  161,317  322,442      393,365               653,978   -50.0
27        Porsche   12,193   15,233       24,177                30,257   -20.0
28            Ram  127,682  196,155      268,168               333,168   -34.9
29          Smart        0      244            0                   475  -100.0
30         Subaru  136,519  182,771      318,568               339,525   -25.3
31          Tesla   36,800   53,300       89,600                83,900   -31.0
32         Toyota  347,571  539,448      933,017             1,016,373   -35.6
33     Volkswagen   69,933   98,736      144,998               184,608   -29.2
34          Volvo   23,770   28,062       52,952                50,120   -15.3

In [16]:
#merge the two data sources into one dataframe
Auto_Sales = pd.merge(SummaryTable, Auto_Sales_Table, how = "left", on = "make")
Auto_Sales

,year,make,model,category_list,q2_2020,q2_2019,year_to_date,year_to_date_previous,change
0,2020,Audi,Q3,SUV,"34,839","53,325","76,210","101,440",-34.7
1,2020,Chevrolet,Malibu,Sedan,"330,381","486,884","759,910","938,626",-32.1
2,2020,Cadillac,Escalade ESV,SUV,"23,297","39,739","53,620","75,735",-41.4
3,2020,Chevrolet,Corvette,"Coupe, Convertible","330,381","486,884","759,910","938,626",-32.1
4,2020,Acura,RLX,Sedan,"27,458","37,382","69,065","73,767",-26.5
...,...,...,...,...,...,...,...,...,...
95,2020,INFINITI,Q50,Sedan,NaN,NaN,NaN,NaN,NaN
96,2020,Genesis,G80,Sedan,"3,585","5,805","8,797","10,008",-38.2
97,2020,Jaguar,F-PACE,SUV,"4,320","6,060","11,586","16,282",-28.7
98,2020,Jeep,Renegade,SUV,"176,713","243,477","359,380","456,281",-27.4
99,2020,Hyundai,Accent,Sedan,"139,378","185,743","327,930","333,328",-25.0

In [17]:
#clean dataframe by dropping NaNs and reseting the index
Auto_Sales.dropna(how="any", inplace=True)
Auto_Sales.reset_index(drop=True, inplace=True)
Auto_Sales

,year,make,model,category_list,q2_2020,q2_2019,year_to_date,year_to_date_previous,change
0,2020,Audi,Q3,SUV,"34,839","53,325","76,210","101,440",-34.7
1,2020,Chevrolet,Malibu,Sedan,"330,381","486,884","759,910","938,626",-32.1
2,2020,Cadillac,Escalade ESV,SUV,"23,297","39,739","53,620","75,735",-41.4
3,2020,Chevrolet,Corvette,"Coupe, Convertible","330,381","486,884","759,910","938,626",-32.1
4,2020,Acura,RLX,Sedan,"27,458","37,382","69,065","73,767",-26.5
...,...,...,...,...,...,...,...,...,...
90,2020,Jaguar,I-PACE,SUV,"4,320","6,060","11,586","16,282",-28.7
91,2020,Genesis,G80,Sedan,"3,585","5,805","8,797","10,008",-38.2
92,2020,Jaguar,F-PACE,SUV,"4,320","6,060","11,586","16,282",-28.7
93,2020,Jeep,Renegade,SUV,"176,713","243,477","359,380","456,281",-27.4
94,2020,Hyundai,Accent,Sedan,"139,378","185,743","327,930","333,328",-25.0

In [18]:
#checking data types
Auto_Sales.dtypes

year                       int64
make                      object
model                     object
category_list             object
q2_2020                   object
q2_2019                   object
year_to_date              object
year_to_date_previous     object
change                   float64
dtype: object

In [19]:
#connect to pdAdmin4 PostgreSQL
from sqlalchemy import create_engine

In [20]:
connection_string = "postgres:postgres@localhost:5432/AutoSales_db"
engine = create_engine(f'postgresql://{connection_string}')

In [22]:
# Confirm table in PgAdmin4
engine.table_names()

['auto_sales']

In [24]:
#Output pandas dataframe to PgAdmin4
Auto_Sales.to_sql(name='auto_sales', con=engine, if_exists='append', index=True)

In [25]:
#Confirming data in PgAdmin4
Auto_Sales_Final = pd.read_sql_query('select * from auto_sales', con=engine)

In [26]:
Auto_Sales_Final

,index,year,make,model,category_list,q2_2020,q2_2019,year_to_date,year_to_date_previous,change
0,0,2020,Audi,Q3,SUV,"34,839","53,325","76,210","101,440",-34.7
1,1,2020,Chevrolet,Malibu,Sedan,"330,381","486,884","759,910","938,626",-32.1
2,2,2020,Cadillac,Escalade ESV,SUV,"23,297","39,739","53,620","75,735",-41.4
3,3,2020,Chevrolet,Corvette,"Coupe, Convertible","330,381","486,884","759,910","938,626",-32.1
4,4,2020,Acura,RLX,Sedan,"27,458","37,382","69,065","73,767",-26.5
...,...,...,...,...,...,...,...,...,...,...
90,90,2020,Jaguar,I-PACE,SUV,"4,320","6,060","11,586","16,282",-28.7
91,91,2020,Genesis,G80,Sedan,"3,585","5,805","8,797","10,008",-38.2
92,92,2020,Jaguar,F-PACE,SUV,"4,320","6,060","11,586","16,282",-28.7
93,93,2020,Jeep,Renegade,SUV,"176,713","243,477","359,380","456,281",-27.4
94,94,2020,Hyundai,Accent,Sedan,"139,378","185,743","327,930","333,328",-25.0

In [29]:
#store final data in Excel
Auto_Sales_Final.to_excel(r'/Users/klcurtiss/Desktop/Work for Bootcamp/Rutgers Class Practice/01-Lesson-Plans copy/13-ETL-Project/My ETL Project/Auto_Sales_Final.xlsx', index = False)